// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe5_DDsaxl-xqdVkHP39J87ibJbqOhydE',
    appId: '1:780160909583:web:9aee8087f983149ebe7e7a',
    messagingSenderId: '780160909583',
    projectId: 'echosee-smart-glasses-app',
    authDomain: 'echosee-smart-glasses-app.firebaseapp.com',
    storageBucket: 'echosee-smart-glasses-app.firebasestorage.app',
    measurementId: 'G-PV61FBZ3D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6n1Ct3Rgu01P3n--fH9pzXacc1vTGR2s',
    appId: '1:780160909583:android:fa7e1d662bca927cbe7e7a',
    messagingSenderId: '780160909583',
    projectId: 'echosee-smart-glasses-app',
    storageBucket: 'echosee-smart-glasses-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQRY7bgAfQM4vmo_p7-qhM22PcUgutWV8',
    appId: '1:780160909583:ios:3368ec9ccbdbe580be7e7a',
    messagingSenderId: '780160909583',
    projectId: 'echosee-smart-glasses-app',
    storageBucket: 'echosee-smart-glasses-app.firebasestorage.app',
    iosBundleId: 'com.example.echoseeSmartGlassesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe5_DDsaxl-xqdVkHP39J87ibJbqOhydE',
    appId: '1:780160909583:web:2a9001a07bc3465bbe7e7a',
    messagingSenderId: '780160909583',
    projectId: 'echosee-smart-glasses-app',
    authDomain: 'echosee-smart-glasses-app.firebaseapp.com',
    storageBucket: 'echosee-smart-glasses-app.firebasestorage.app',
    measurementId: 'G-5KQ95ECJDX',
  );
}
